development: &development
  developer: true
  base: "http://localhost:3000"
  return_to: "/pedido/efetuado"
  email: rtimbo@ikwa.com.br

test:
  <<: *development

production:
  authenticity_token: C8ABC3DAE4324C4499115846814505C3
  email: rtimbo@ikwa.com.br
  return_to: "/pedido/efetuado"
